"""Type stubs for medforge — High-performance HL7v2 message parser."""

from __future__ import annotations

class Component:
    """A single component within an HL7v2 field."""

    @property
    def value(self) -> str: ...
    @property
    def sub_components(self) -> list[str]: ...
    def sub_component(self, index: int) -> str:
        """Return sub-component at 1-based index."""
        ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Field:
    """A single field within an HL7v2 segment."""

    @property
    def value(self) -> str: ...
    @property
    def components(self) -> list[Component]: ...
    @property
    def repetitions(self) -> list[Field]: ...
    def component(self, index: int) -> Component:
        """Return component at 1-based index."""
        ...
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Component: ...

class Segment:
    """A single segment within an HL7v2 message (e.g. MSH, PID, OBX)."""

    @property
    def name(self) -> str: ...
    @property
    def fields(self) -> list[Field]: ...
    def field(self, index: int) -> Field:
        """Return field at 1-based index."""
        ...
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Field: ...

class Message:
    """A parsed HL7v2 message."""

    @property
    def raw(self) -> str: ...
    @property
    def segments(self) -> list[Segment]: ...
    @property
    def message_type(self) -> tuple[str, str]:
        """Message type from MSH-9, e.g. ("ADT", "A01")."""
        ...
    @property
    def control_id(self) -> str:
        """Message control ID from MSH-10."""
        ...
    @property
    def version(self) -> str:
        """HL7 version from MSH-12."""
        ...
    @property
    def sending_application(self) -> str:
        """Sending application from MSH-3."""
        ...
    @property
    def sending_facility(self) -> str:
        """Sending facility from MSH-4."""
        ...
    def segment(self, name: str) -> Segment:
        """Return the first segment matching the given name."""
        ...
    def segments_by_name(self, name: str) -> list[Segment]:
        """Return all segments matching the given name."""
        ...
    def get(self, path: str) -> str:
        """Terser path access: 'PID-5-1' or 'PID-5'."""
        ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __getitem__(self, path: str) -> str:
        """Terser path access via bracket notation."""
        ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

def parse(raw: str) -> Message:
    """Parse a raw HL7v2 message string into a Message object.

    Handles MLLP-framed input automatically. Supports \\r, \\n, and \\r\\n
    segment delimiters.
    """
    ...
